name: app_streaming
description: "Streaming app clone"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1  
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  youtube_player_flutter: ^8.0.0
  http: ^1.2.1
  cached_network_image: ^3.1.0
  provider: ^6.0.0
  firebase_core: ^2.15.0  
  firebase_auth: ^4.8.2  
  webview_flutter: ^4.0.0
  flutter_inappwebview: ^5.3.2 # Or the latest version
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  assets: 
    - assets/netflix_logo.svg
