// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS6Cb3TIf5inKryFVdljoKnK22lNMLMRg',
    appId: '1:135973407805:web:20d0085d5df4a1ea00ee54',
    messagingSenderId: '135973407805',
    projectId: 'app-streaming-tds',
    authDomain: 'app-streaming-tds.firebaseapp.com',
    storageBucket: 'app-streaming-tds.appspot.com',
    measurementId: 'G-4D6TGW0TQD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJoEF_BgDNeSzr3AygwBF23Fn1WFT0X-E',
    appId: '1:135973407805:ios:072a5dd124d9cb1900ee54',
    messagingSenderId: '135973407805',
    projectId: 'app-streaming-tds',
    storageBucket: 'app-streaming-tds.appspot.com',
    iosBundleId: 'com.example.appStreaming',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJoEF_BgDNeSzr3AygwBF23Fn1WFT0X-E',
    appId: '1:135973407805:ios:072a5dd124d9cb1900ee54',
    messagingSenderId: '135973407805',
    projectId: 'app-streaming-tds',
    storageBucket: 'app-streaming-tds.appspot.com',
    iosBundleId: 'com.example.appStreaming',
  );
}
